name: jsonize
description: A JSON serialize class to convert 'to' and 'from' JSON format Enums, DateTime, Duration and any of your own classes.
version: 1.7.2+1
homepage: https://github.com/cabbi/jsonize

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  http: ^1.1.0
