name: jsonize
description: A json serialize class to convert 'to' and 'from' json format DateTime and any of your own classes.
version: 1.2.0
homepage: https://github.com/cabbi/jsonize

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
